<script setup>
import {
  FilePlus2,
  FileUp,
  FileText,
  FileType,
  BookOpenCheck,
  DatabaseBackup,
  HardDrive,
  Map,
  LayoutPanelTop,
  Dices,
  HelpCircle,
  Plus,
  Unlink,
  BookMarked,
  Files,
  FileQuestion,
  GitBranch,
  History,
  ListTree,
  PanelsTopLeft,
  Columns2,
  ScanEye,
  SquarePen,
  UserRound,
  UsersRound,
  MessageCircleQuestion,
  NotebookPen,
  LibraryBig,
  Archive,
  ArrowLeft,
  ArrowRight,
  BookmarkPlus,
  BookOpen,
  Clapperboard,
  ChevronDown,
  LayoutGrid,
  List,
  Compass,
  Download,
  Film,
  Folder,
  Image,
  Menu,
  Moon,
  Sun,
  MessageSquareText,
  MoreHorizontal,
  PanelLeft,
  Palette,
  Pencil,
  Pin,
  RefreshCw,
  Search,
  RotateCcw,
  Network,
  Settings,
  Sparkles,
  Trash2,
  Users,
  X,
  ZoomIn,
  ZoomOut
} from 'lucide-vue-next'

const icons = {
  'new-manuscript': FilePlus2,
  'import-manuscript': FileUp,
  document: FileText,
  markdown: FileType,
  guide: BookOpenCheck,
  backup: DatabaseBackup,
  storage: HardDrive,
  map: Map,
  comics: LayoutPanelTop,
  adventure: Dices,
  help: HelpCircle,
  plus: Plus,
  unlink: Unlink,
  writing: NotebookPen,
  worldbook: BookMarked,
  sources: Files,
  outline: ListTree,
  character: UserRound,
  collaboration: UsersRound,
  annotation: SquarePen,
  rehearsal: GitBranch,
  scene: ScanEye,
  assistant: MessageCircleQuestion,
  history: History,
  columns: Columns2,
  canvas: PanelsTopLeft,
  library: LibraryBig,
  'chevron-down': ChevronDown,
  grid: LayoutGrid,
  list: List,
  archive: Archive,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'bookmark-plus': BookmarkPlus,
  book: BookOpen,
  compass: Compass,
  download: Download,
  film: Film,
  folder: Folder,
  image: Image,
  menu: Menu,
  moon: Moon,
  sun: Sun,
  'message-square': MessageSquareText,
  more: MoreHorizontal,
  network: Network,
  'panel-left': PanelLeft,
  palette: Palette,
  pencil: Pencil,
  pin: Pin,
  refresh: RefreshCw,
  search: Search,
  'undo-extension': RotateCcw,
  settings: Settings,
  sparkles: Sparkles,
  storyboard: Clapperboard,
  trash: Trash2,
  users: Users,
  close: X,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut
}

defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 16 },
  strokeWidth: { type: [Number, String], default: 1.7 }
})
</script>

<template>
  <component
    :is="icons[name] || FileQuestion"
    class="workbench-icon"
    :size="size"
    :stroke-width="strokeWidth"
    aria-hidden="true"
    focusable="false"
  />
</template>

<style scoped>
.workbench-icon { display: block; flex-shrink: 0; }
</style>
